language: node_js
node_js:
  - 8.4.0
cache:
  directories:
    - node_modules
branches:
  only:
  - master
before_install:
  - echo "Starting deployment processes..."
install:
  - npm install
script:
  - node index.js